CREATE TABLE `pergunta` (
  `id_perguntas` int(11) NOT NULL,
  `questao` tinytext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

use scadae;

INSERT INTO `pergunta` (`id_perguntas`, `questao`) VALUES
(1, 'Ano de nascimento'),
(2, 'Ano de ingresso no curso'),
(3, 'Ano de conclusão do curso'),
(4, 'Estado civil'),
(5, 'Sexo'),
(6, 'País onde mora'),
(7, 'Estado onde mora'),
(8, 'Você fez curso técnico antes da graduação?'),
(9, 'O curso técnico foi na área da computação?'),
(10, 'O curso técnico auxiliou na gradução?'),
(11, 'Você publicou artigo durante a graduação?'),
(12, 'Qual foi o formato da sua defesa de TCC?'),
(13, 'Fez estágio na área da computação durante a graduação?'),
(14, 'Participou da Empresa Jr. (SetApp) na graduação?'),
(15, 'Você participou como membro discente em entidades representativas de discentes?'),
(16, 'Você participou de algum projeto de iniciação científica?'),
(17, 'Você participou de algum projeto de extensão?'),
(18, 'Você participou de algum projeto de ensino?'),
(19, 'Você foi monitor ou tutor em alguma disciplina?'),
(20, 'Você fez intercâmbio durante a gradução?'),
(21, 'Para onde você foi no intercâmbio? (Estado se foi feito no Brasil e o país de foi feito no exterior)?'),
(22, 'Você continuou os seus estudos?'),
(23, 'Língua estrangeira que sabe ler'),
(24, 'Língua estrangeira que sabe falar'),
(25, 'Língua estrangeira que sabe escrever'),
(26, 'Quantos cursos/treinamentos você costuma fazer por ano?'),
(27, 'Quantas palestras/congressos você costuma ir por ano?'),
(28, 'Você estaria disposto a participar como palestrante da semana acadêmica do curso que é realizada anualmente no mês de maio?'),
(29, 'Qual seria o tema dessa palestra?'),
(30, 'Você estaria disposto a ministrar um minicurso da semana acadêmica do curso que é realizada anualmente no mês de maio?'),
(31, 'Qual seria o tema deste minicurso?'),
(32, 'Você já trabalhou?'),
(33, 'Quando foi o início da sua atividade profissional?'),
(34, 'Como obteve o primeiro emprego?'),
(35, 'Você está trabalhando?'),
(36, 'Qual o seu vínculo empregatício?'),
(37, 'Qual a área que você atua?'),
(38, 'A função que você exerce está alinhada com a Ciência da Computação?'),
(39, 'Qual o cargo você ocupa?'),
(40, 'Quantas horas você trabalha por semana?'),
(41, 'Qual a sua faixa salarial bruta?'),
(42, 'Avalie como foram as dificuldades que você encontrou na profissão'),
(43, 'Qual o principal motivo para você não atuar na área da computação?'),
(44, 'Por que você não está empregado?'),
(45, 'Qual o ramo da empresa que você trabalha?'),
(46, 'Quantas pessoas trabalham na empresa?'),
(47, 'Classifique os itens de acordo com a importância deles para entrada no mercado de trabalho'),
(48, 'Como os itens abaixo ofereceram uma base diferenciada comparada com os seus colegas de trabalho?'),
(49, 'Com qual frequência você utiliza as disciplinas abaixo no seu ambiente de trabalho?'),
(50, 'Com qual frequência você utiliza as seguintes linguagens de programação no seu trabalho?'),
(51, 'Com qual frequência você utiliza os seguintes SGBD no seu trabalho?'),
(52, 'Com qual frequência você utiliza os seguintes sistemas operacionais no seu trabalho?'),
(53, 'Você fuma?'),
(54, 'Você faz algum trabalho voluntário?'),
(55, 'Qual a sua média de sono?'),
(56, 'Você pratica esporte?'),
(57, 'Quais esporte abaixo você pratica?'),
(58, 'Classifique as opções abaixo de acordo com o grau de influência dela na sua escolha em cursar o Bacharel em Ciência da Computação'),
(59, 'Classifique as opções abaixo de acordo com o grau de influência dela na sua escolha de estudar na Universidade Federal de Viçosa - Campus Florestal'),
(60, 'Como foi atendida suas expectativas do curso em relação à formação profissional?'),
(61, 'As disciplinas específicas foram adequadas para o bom desempenho da atividade profissional?'),
(62, 'Como você classifica os itens abaixo'),
(63, 'Como você avalia a importância dessa pesquisa?'),
(64, 'Já iniciou outro curso técnico?'),
(65, 'Já concluiu outro curso técnico?'),
(66, 'Você teve bolsa do Pibic ou Pibex'),
(67, 'Você fez o técnico concomitante ou subsequente?'),
(68, 'Você já atuou como técnico em informática?'),
(69, 'A função que você exerce está alinhada com o Técnico em Informática?'),
(70, 'Qual o principal motivo para você não atuar na área de informática?'),
(71, 'Classifique as opções abaixo de acordo com o grau de influência dela na sua escolha em cursar o Técnico em Informática'),
(72, 'Classifique as opções abaixo de acordo com o grau de influência dela na sua escolha de estudar na Cedaf'),
(73, 'Você acha que o estágio de pelo menos 150h (além das disciplinas obrigatórias) deve ser obrigatório para receber o diploma do curso?'),
(74, 'Você acha que o curso deve ter 120h em atividades complementares obrigatórias? Essas atividades são relacionadas à Informática, mas realizadas fora do horário de aula e para isso haveria a diminuição de 120h das disciplinas normais do curso.');
