<?php
    include '../acessobancosup.php';
    include 'vSuperior.php';

    $teste_tecnologiasup = "SELECT * 
                            FROM resposta
	                        WHERE CPF = '$cpf' AND id_perguntas = (SELECT id_perguntas 
                                                                   FROM pergunta 
                                                                   WHERE numeracao = 50)";
	          
    $verifica_tecnologiasup = mysqli_query($conn, $teste_tecnologiasup);

    if (mysqli_num_rows($verifica_tecnologiasup) >= 1){
        $delete50 = "DELETE FROM resposta WHERE cpf = '$cpf' AND id_perguntas = (SELECT id_perguntas FROM pergunta WHERE numeracao = 50);";
        $delete51 = "DELETE FROM resposta WHERE cpf = '$cpf' AND id_perguntas = (SELECT id_perguntas FROM pergunta WHERE numeracao = 51);";
        $delete52 = "DELETE FROM resposta WHERE cpf = '$cpf' AND id_perguntas = (SELECT id_perguntas FROM pergunta WHERE numeracao = 52);"; 
        
        $d50 = mysqli_query($conn, $delete50);
        $d51 = mysqli_query($conn, $delete51);
        $d52 = mysqli_query($conn, $delete52);
    }
                
    $opt50A = filter_input (INPUT_POST, '50A', FILTER_SANITIZE_STRING);
    $opt50B = filter_input (INPUT_POST, '50B', FILTER_SANITIZE_STRING);
    $opt50C = filter_input (INPUT_POST, '50C', FILTER_SANITIZE_STRING);
    $opt50D = filter_input (INPUT_POST, '50D', FILTER_SANITIZE_STRING);
    $opt50E = filter_input (INPUT_POST, '50E', FILTER_SANITIZE_STRING);
    $opt50F = filter_input (INPUT_POST, '50F', FILTER_SANITIZE_STRING);
    $opt50G = filter_input (INPUT_POST, '50G', FILTER_SANITIZE_STRING);
    $opt50H = filter_input (INPUT_POST, '50H', FILTER_SANITIZE_STRING);
    $opt50I = filter_input (INPUT_POST, '50I', FILTER_SANITIZE_STRING);
    $opt50J = filter_input (INPUT_POST, '50J', FILTER_SANITIZE_STRING);
    $opt50K = filter_input (INPUT_POST, '50K', FILTER_SANITIZE_STRING);
    $opt50L = filter_input (INPUT_POST, '50L', FILTER_SANITIZE_STRING);
    $opt50M = filter_input (INPUT_POST, '50M', FILTER_SANITIZE_STRING);
    $opt50N = filter_input (INPUT_POST, '50N', FILTER_SANITIZE_STRING);
    $opt50O = filter_input (INPUT_POST, '50O', FILTER_SANITIZE_STRING);
    $opt50P = filter_input (INPUT_POST, '50P', FILTER_SANITIZE_STRING);
    $opt50Q = filter_input (INPUT_POST, '50Q', FILTER_SANITIZE_STRING);
    $opt50R = filter_input (INPUT_POST, '50R', FILTER_SANITIZE_STRING);
    $opt50S = filter_input (INPUT_POST, '50S', FILTER_SANITIZE_STRING);
    $opt50T = filter_input (INPUT_POST, '50T', FILTER_SANITIZE_STRING);
    $opt50U = filter_input (INPUT_POST, '50U', FILTER_SANITIZE_STRING);
    $opt50V = filter_input (INPUT_POST, '50V', FILTER_SANITIZE_STRING);
    $opt50W = filter_input (INPUT_POST, '50W', FILTER_SANITIZE_STRING);
    $opt51A = filter_input (INPUT_POST, '51A', FILTER_SANITIZE_STRING);
    $opt51B = filter_input (INPUT_POST, '51B', FILTER_SANITIZE_STRING);
    $opt51C = filter_input (INPUT_POST, '51C', FILTER_SANITIZE_STRING);
    $opt51D = filter_input (INPUT_POST, '51D', FILTER_SANITIZE_STRING);
    $opt51E = filter_input (INPUT_POST, '51E', FILTER_SANITIZE_STRING);
    $opt51F = filter_input (INPUT_POST, '51F', FILTER_SANITIZE_STRING);
    $opt51G = filter_input (INPUT_POST, '51G', FILTER_SANITIZE_STRING);
    $opt51H = filter_input (INPUT_POST, '51H', FILTER_SANITIZE_STRING);
    $opt51I = filter_input (INPUT_POST, '51I', FILTER_SANITIZE_STRING);
    $opt51J = filter_input (INPUT_POST, '51J', FILTER_SANITIZE_STRING);
    $opt51K = filter_input (INPUT_POST, '51K', FILTER_SANITIZE_STRING);
    $opt52A = filter_input (INPUT_POST, '52A', FILTER_SANITIZE_STRING);
    $opt52B = filter_input (INPUT_POST, '52B', FILTER_SANITIZE_STRING);
    $opt52C = filter_input (INPUT_POST, '52C', FILTER_SANITIZE_STRING);
    $opt52D = filter_input (INPUT_POST, '52D', FILTER_SANITIZE_STRING);
    $opt52E = filter_input (INPUT_POST, '52E', FILTER_SANITIZE_STRING);
    $opt52F = filter_input (INPUT_POST, '52F', FILTER_SANITIZE_STRING);
                
    $insert50A = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50A' AND numeracao = 50 AND numero = 'A'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'A' AND alternativa = '$opt50A'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'A' AND numeracao = 50));";
    $insert50B = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50B' AND numeracao = 50 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'B' AND alternativa = '$opt50B'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'B' AND numeracao = 50));";
    $insert50C = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50C' AND numeracao = 50 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'C' AND alternativa = '$opt50C'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'C' AND numeracao = 50));";
    $insert50D = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50D' AND numeracao = 50 AND numero = 'D'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'D' AND alternativa = '$opt50D'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'D' AND numeracao = 50));";
    $insert50E = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50E' AND numeracao = 50 AND numero = 'E'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'E' AND alternativa = '$opt50E'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'E' AND numeracao = 50));";
    $insert50F = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50F' AND numeracao = 50 AND numero = 'F'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'F' AND alternativa = '$opt50F'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'F' AND numeracao = 50));";
    $insert50G = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50G' AND numeracao = 50 AND numero = 'G'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'G' AND alternativa = '$opt50G'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'G' AND numeracao = 50));";
    $insert50H = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50H' AND numeracao = 50 AND numero = 'H'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'H' AND alternativa = '$opt50H'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'H' AND numeracao = 50));";
    $insert50I = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50I' AND numeracao = 50 AND numero = 'I'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'I' AND alternativa = '$opt50I'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'I' AND numeracao = 50));";
    $insert50J = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50J' AND numeracao = 50 AND numero = 'J'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'J' AND alternativa = '$opt50J'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'J' AND numeracao = 50));";
    $insert50K = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50K' AND numeracao = 50 AND numero = 'K'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'K' AND alternativa = '$opt50K'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'K' AND numeracao = 50));";
    $insert50L = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50L' AND numeracao = 50 AND numero = 'L'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'L' AND alternativa = '$opt50L'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'L' AND numeracao = 50));";
    $insert50M = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50M' AND numeracao = 50 AND numero = 'M'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'M' AND alternativa = '$opt50M'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'M' AND numeracao = 50));";
    $insert50N = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50N' AND numeracao = 50 AND numero = 'N'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'N' AND alternativa = '$opt50N'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'N' AND numeracao = 50));";
    $insert50O = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50O' AND numeracao = 50 AND numero = 'O'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'O' AND alternativa = '$opt50O'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'O' AND numeracao = 50));";
    $insert50P = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50P' AND numeracao = 50 AND numero = 'P'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'P' AND alternativa = '$opt50P'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'P' AND numeracao = 50));";
    $insert50Q = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50Q' AND numeracao = 50 AND numero = 'Q'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'Q' AND alternativa = '$opt50Q'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'Q' AND numeracao = 50));";
    $insert50R = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50R' AND numeracao = 50 AND numero = 'R'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'R' AND alternativa = '$opt50R'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'R' AND numeracao = 50));";
    $insert50S = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50S' AND numeracao = 50 AND numero = 'S'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'S' AND alternativa = '$opt50S'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'S' AND numeracao = 50));";
    $insert50T = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50T' AND numeracao = 50 AND numero = 'T'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'T' AND alternativa = '$opt50T'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'T' AND numeracao = 50));";
    $insert50U = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50U' AND numeracao = 50 AND numero = 'U'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'U' AND alternativa = '$opt50U'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'U' AND numeracao = 50));";
    $insert50V = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50V' AND numeracao = 50 AND numero = 'V'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'V' AND alternativa = '$opt50V'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'V' AND numeracao = 50));";
    $insert50W = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt50W' AND numeracao = 50 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 50), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 50 AND numero = 'W' AND alternativa = '$opt50W'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'W' AND numeracao = 50));";
    $insert51A = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51A' AND numeracao = 51 AND numero = 'A'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'A' AND alternativa = '$opt51A'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'A' AND numeracao = 51));";
    $insert51B = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51B' AND numeracao = 51 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'B' AND alternativa = '$opt51B'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'B' AND numeracao = 51));";
    $insert51C = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51C' AND numeracao = 51 AND numero = 'C'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'C' AND alternativa = '$opt51C'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'C' AND numeracao = 51));";
    $insert51D = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51D' AND numeracao = 51 AND numero = 'D'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'D' AND alternativa = '$opt51D'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'D' AND numeracao = 51));";
    $insert51E = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51E' AND numeracao = 51 AND numero = 'E'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'E' AND alternativa = '$opt51E'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'E' AND numeracao = 51));";
    $insert51F = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51F' AND numeracao = 51 AND numero = 'F'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'F' AND alternativa = '$opt51F'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'F' AND numeracao = 51));";
    $insert51G = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51G' AND numeracao = 51 AND numero = 'G'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'G' AND alternativa = '$opt51G'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'G' AND numeracao = 51));";
    $insert51H = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51H' AND numeracao = 51 AND numero = 'H'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'H' AND alternativa = '$opt51H'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'H' AND numeracao = 51));";
    $insert51I = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51I' AND numeracao = 51 AND numero = 'I'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'I' AND alternativa = '$opt51I'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'I' AND numeracao = 51));";
    $insert51J = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51J' AND numeracao = 51 AND numero = 'J'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'J' AND alternativa = '$opt51J'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'J' AND numeracao = 51));";
    $insert51K = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt51K' AND numeracao = 51 AND numero = 'K'), (SELECT id_perguntas FROM pergunta where numeracao = 51), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 51 AND numero = 'K' AND alternativa = '$opt51K'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'K' AND numeracao = 51));";
    $insert52A = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt52A' AND numeracao = 52 AND numero = 'A'), (SELECT id_perguntas FROM pergunta where numeracao = 52), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 52 AND numero = 'A' AND alternativa = '$opt52A'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'A' AND numeracao = 52));";
    $insert52B = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt52B' AND numeracao = 52 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 52), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 52 AND numero = 'B' AND alternativa = '$opt52B'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'B' AND numeracao = 52));";
    $insert52C = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt52C' AND numeracao = 52 AND numero = 'C'), (SELECT id_perguntas FROM pergunta where numeracao = 52), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 52 AND numero = 'C' AND alternativa = '$opt52C'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'C' AND numeracao = 52));";
    $insert52D = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt52D' AND numeracao = 52 AND numero = 'D'), (SELECT id_perguntas FROM pergunta where numeracao = 52), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 52 AND numero = 'D' AND alternativa = '$opt52D'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'D' AND numeracao = 52));";
    $insert52E = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt52E' AND numeracao = 52 AND numero = 'E'), (SELECT id_perguntas FROM pergunta where numeracao = 52), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 52 AND numero = 'E' AND alternativa = '$opt52E'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'E' AND numeracao = 52));";
    $insert52F = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt52F' AND numeracao = 52 AND numero = 'F'), (SELECT id_perguntas FROM pergunta where numeracao = 52), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 52 AND numero = 'F' AND alternativa = '$opt52F'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'F' AND numeracao = 52));";
                
    $resultado50A = mysqli_query($conn, $insert50A);
    $resultado50B = mysqli_query($conn, $insert50B);
    $resultado50C = mysqli_query($conn, $insert50C);
    $resultado50D = mysqli_query($conn, $insert50D);
    $resultado50E = mysqli_query($conn, $insert50E);
    $resultado50F = mysqli_query($conn, $insert50F);
    $resultado50G = mysqli_query($conn, $insert50G);
    $resultado50H = mysqli_query($conn, $insert50H);
    $resultado50I = mysqli_query($conn, $insert50I);
    $resultado50J = mysqli_query($conn, $insert50J);
    $resultado50K = mysqli_query($conn, $insert50K);
    $resultado50L = mysqli_query($conn, $insert50L);
    $resultado50M = mysqli_query($conn, $insert50M);
    $resultado50N = mysqli_query($conn, $insert50N);
    $resultado50O = mysqli_query($conn, $insert50O);
    $resultado50P = mysqli_query($conn, $insert50P);
    $resultado50Q = mysqli_query($conn, $insert50Q);
    $resultado50R = mysqli_query($conn, $insert50R);
    $resultado50S = mysqli_query($conn, $insert50S);
    $resultado50T = mysqli_query($conn, $insert50T);
    $resultado50U = mysqli_query($conn, $insert50U);
    $resultado50V = mysqli_query($conn, $insert50V);
    $resultado50W = mysqli_query($conn, $insert50W);
    $resultado51A = mysqli_query($conn, $insert51A);
    $resultado51B = mysqli_query($conn, $insert51B);
    $resultado51C = mysqli_query($conn, $insert51C);
    $resultado51D = mysqli_query($conn, $insert51D);
    $resultado51E = mysqli_query($conn, $insert51E);
    $resultado51F = mysqli_query($conn, $insert51F);
    $resultado51G = mysqli_query($conn, $insert51G);
    $resultado51H = mysqli_query($conn, $insert51H);
    $resultado51I = mysqli_query($conn, $insert51I);
    $resultado51J = mysqli_query($conn, $insert51J);
    $resultado51K = mysqli_query($conn, $insert51K);
    $resultado52A = mysqli_query($conn, $insert52A);
    $resultado52B = mysqli_query($conn, $insert52B);
    $resultado52C = mysqli_query($conn, $insert52C);
    $resultado52D = mysqli_query($conn, $insert52D);
    $resultado52E = mysqli_query($conn, $insert52E);
    $resultado52F = mysqli_query($conn, $insert52F);

    mysqli_close($conn);

    //header ("Location: lazersup.php");
?>

<!DOCTYPE HTML>
<html lang = "pt-br">
  <head>
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity = "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin = "anonymous"> 
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity = "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin = "anonymous">
    <link rel = "stylesheet" href = "../estilo.css">
    <link rel = "stylesheet" href = "superior.css">

    <title>Questionario</title>
	</head>
	<body>
        <?php
            echo $opt50J;
        ?>
    </body>
</html>