use scadae;

INSERT INTO `alternativa` (`id_alternativa`, `alternativa`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Antes de 1980', NULL, NULL, NULL),
(2, 'Antes de 1990', NULL, NULL, NULL),
(3, '1980', NULL, NULL, NULL),
(4, '1981', NULL, NULL, NULL),
(5, '1982', NULL, NULL, NULL),
(6, '1983', NULL, NULL, NULL),
(7, '1984', NULL, NULL, NULL),
(8, '1985', NULL, NULL, NULL),
(9, '1986', NULL, NULL, NULL),
(10, '1987', NULL, NULL, NULL),
(11, '1988', NULL, NULL, NULL),
(12, '1989', NULL, NULL, NULL),
(13, '1990', NULL, NULL, NULL),
(14, '1991', NULL, NULL, NULL),
(15, '1992', NULL, NULL, NULL),
(16, '1993', NULL, NULL, NULL),
(17, '1994', NULL, NULL, NULL),
(18, '1995', NULL, NULL, NULL),
(19, '1996', NULL, NULL, NULL),
(20, '1997', NULL, NULL, NULL),
(21, '1998', NULL, NULL, NULL),
(22, '1999', NULL, NULL, NULL),
(23, '2000', NULL, NULL, NULL),
(24, '2001', NULL, NULL, NULL),
(25, '2002', NULL, NULL, NULL),
(26, '2003', NULL, NULL, NULL),
(27, '2004', NULL, NULL, NULL),
(28, '2005', NULL, NULL, NULL),
(29, '2006', NULL, NULL, NULL),
(30, '2007', NULL, NULL, NULL),
(31, '2008', NULL, NULL, NULL),
(32, '2009', NULL, NULL, NULL),
(33, '2010', NULL, NULL, NULL),
(34, '2011', NULL, NULL, NULL),
(35, '2012', NULL, NULL, NULL),
(36, '2013', NULL, NULL, NULL),
(37, '2014', NULL, NULL, NULL),
(38, '2015', NULL, NULL, NULL),
(39, '2016', NULL, NULL, NULL),
(40, '2017', NULL, NULL, NULL),
(41, '2018', NULL, NULL, NULL),
(42, '2019', NULL, NULL, NULL),
(43, '2020', NULL, NULL, NULL),
(44, '2021', NULL, NULL, NULL),
(45, '2022', NULL, NULL, NULL),
(46, '2023', NULL, NULL, NULL),
(47, 'Solteiro', NULL, NULL, NULL),
(48, 'União estável', NULL, NULL, NULL),
(49, 'Casado', NULL, NULL, NULL),
(50, 'Divorciado', NULL, NULL, NULL),
(51, 'Viúvo', NULL, NULL, NULL),
(52, 'Feminino', NULL, NULL, NULL),
(53, 'Masculino', NULL, NULL, NULL),
(54, 'Prefiro não informar', NULL, NULL, NULL),
(55, 'Outro', NULL, NULL, NULL),
(56, 'Brasil', NULL, NULL, NULL),
(57, 'Canadá', NULL, NULL, NULL),
(58, 'Espanha', NULL, NULL, NULL),
(59, 'Estados Unidos', NULL, NULL, NULL),
(60, 'França', NULL, NULL, NULL),
(61, 'Itália', NULL, NULL, NULL),
(62, 'Portugal', NULL, NULL, NULL),
(63, 'Acre', NULL, NULL, NULL),
(64, 'Alagoas', NULL, NULL, NULL),
(65, 'Amazonas', NULL, NULL, NULL),
(66, 'Amapá', NULL, NULL, NULL),
(67, 'Bahia', NULL, NULL, NULL),
(68, 'Ceará', NULL, NULL, NULL),
(69, 'Distrito Federal', NULL, NULL, NULL),
(70, 'Espírito Santo', NULL, NULL, NULL),
(71, 'Goiás', NULL, NULL, NULL),
(72, 'Maranhão', NULL, NULL, NULL),
(73, 'Mato Grosso', NULL, NULL, NULL),
(74, 'Mato Grosso do Sul', NULL, NULL, NULL),
(75, 'Minas Gerais', NULL, NULL, NULL),
(76, 'Pará', NULL, NULL, NULL),
(77, 'Paraná', NULL, NULL, NULL),
(78, 'Paraiba', NULL, NULL, NULL),
(79, 'Pernambuco', NULL, NULL, NULL),
(80, 'Piauí', NULL, NULL, NULL),
(81, 'Rio de Janeiro', NULL, NULL, NULL),
(82, 'Rio Grande do Norte', NULL, NULL, NULL),
(83, 'Rio Grande do Sul', NULL, NULL, NULL),
(84, 'Rondonia', NULL, NULL, NULL),
(85, 'Roraima', NULL, NULL, NULL),
(86, 'Santa Catarina', NULL, NULL, NULL),
(87, 'Sergipe', NULL, NULL, NULL),
(88, 'São Paulo', NULL, NULL, NULL),
(89, 'Tocantins', NULL, NULL, NULL),
(90, 'Antes da graduação', NULL, NULL, NULL),
(91, 'Durante a graduação', NULL, NULL, NULL),
(92, 'Antes de iniciar o técnico', NULL, NULL, NULL),
(93, 'Durante o técnico', NULL, NULL, NULL),
(94, 'Até um ano depois da formatura', NULL, NULL, NULL),
(95, '1 a 3 anos depois da formatura', NULL, NULL, NULL),
(96, 'Mais de 3 anos depois da formatura', NULL, NULL, NULL),
(97, 'Sim', NULL, NULL, NULL),
(98, 'Não', NULL, NULL, NULL),
(99, 'Indiferente', NULL, NULL, NULL),
(100, 'Outra área, mas na área das exatas', NULL, NULL, NULL),
(101, 'Outra área diferente', NULL, NULL, NULL),
(102, 'Ajudou muito', NULL, NULL, NULL),
(103, 'Ajudou pouco', NULL, NULL, NULL),
(104, 'Não ajudou', NULL, NULL, NULL),
(105, 'Outra graduação', NULL, NULL, NULL),
(106, 'Pós-graduação', NULL, NULL, NULL),
(107, 'Mestrado', NULL, NULL, NULL),
(108, 'Doutorado', NULL, NULL, NULL),
(109, 'Outra formação', NULL, NULL, NULL),
(110, 'Outro técnico', NULL, NULL, NULL),
(111, 'Graduação', NULL, NULL, NULL),
(112, 'Não sei', NULL, NULL, NULL),
(113, 'Básico', NULL, NULL, NULL),
(114, 'Intermediário', NULL, NULL, NULL),
(115, 'Fluente', NULL, NULL, NULL),
(116, '0', NULL, NULL, NULL),
(117, '1', NULL, NULL, NULL),
(118, '2', NULL, NULL, NULL),
(119, '3', NULL, NULL, NULL),
(120, 'Mais de 3', NULL, NULL, NULL),
(121, 'Abriu uma empresa', NULL, NULL, NULL),
(122, 'Enviou currículo e foi selecionado', NULL, NULL, NULL),
(123, 'Fez estágio e foi admitido ao término do mesmo.', NULL, NULL, NULL),
(124, 'Indicação de um amigo', NULL, NULL, NULL),
(125, 'Indicação de um professor', NULL, NULL, NULL),
(126, '4', NULL, NULL, NULL),
(127, '5', NULL, NULL, NULL),
(128, 'Sim. Pibic', NULL, NULL, NULL),
(129, 'Sim. Pibex', NULL, NULL, NULL),
(130, 'Sim. Ambas', NULL, NULL, NULL),
(131, 'Concomitante', NULL, NULL, NULL),
(132, 'Subsequente', NULL, NULL, NULL),
(133, 'Autônomo', NULL, NULL, NULL),
(134, 'Empregado com carteira assinada', NULL, NULL, NULL),
(135, 'Empregado sem carteira assinada', NULL, NULL, NULL),
(136, 'Empregador', NULL, NULL, NULL),
(137, 'Informática/ Sistemas/ Tecnologia', NULL, NULL, NULL),
(138, 'Planejamento/ Desenvolvimento/ Análise', NULL, NULL, NULL),
(139, 'Industrial/ Produção/ Manutenção', NULL, NULL, NULL),
(140, 'Acadêmica', NULL, NULL, NULL),
(141, 'Administração', NULL, NULL, NULL),
(142, 'Comercial/ Vendas', NULL, NULL, NULL),
(143, 'Consultoria', NULL, NULL, NULL),
(144, 'Jurídica/ Legal', NULL, NULL, NULL),
(145, 'Presidência/ Diretoria/ Gerência Geral', NULL, NULL, NULL),
(146, 'Telecomunicações', NULL, NULL, NULL),
(147, 'Acadêmico', NULL, NULL, NULL),
(148, 'Administrador de banco de dados', NULL, NULL, NULL),
(149, 'Administrador de redes', NULL, NULL, NULL),
(150, 'Analista de sistemas', NULL, NULL, NULL),
(151, 'Coordenador de projetos', NULL, NULL, NULL),
(152, 'Diretor', NULL, NULL, NULL),
(153, 'Gerente', NULL, NULL, NULL),
(154, 'Programador', NULL, NULL, NULL),
(155, 'Sócio/ Proprietário', NULL, NULL, NULL),
(156, 'Suporte técnico', NULL, NULL, NULL),
(157, 'Menos de 40', NULL, NULL, NULL),
(158, 'Entre 40 e 44', NULL, NULL, NULL),
(159, 'Entre 45 e 48', NULL, NULL, NULL),
(160, 'Mais de 48', NULL, NULL, NULL),
(161, 'Menos de R$1000,00', NULL, NULL, NULL),
(162, 'Entre R$1000,00 e R$1999,00', NULL, NULL, NULL),
(163, 'Entre R$2000,00 e R$3999,00', NULL, NULL, NULL),
(164, 'Entre R$4000,00 e R$5999,00', NULL, NULL, NULL),
(165, 'Mais de R$6000,00', NULL, NULL, NULL),
(166, 'Menos de R$2000,00', NULL, NULL, NULL),
(167, 'Entre R$2000,00 e R$4999,00', NULL, NULL, NULL),
(168, 'Entre R$5000,00 e R$7999,00', NULL, NULL, NULL),
(169, 'Entre R$8000,00 e R$12000,00', NULL, NULL, NULL),
(170, 'Mais de R$12000,00', NULL, NULL, NULL),
(171, 'Falta de perspectiva de carreira', NULL, NULL, NULL),
(172, 'Melhor oportunidade em outra profissão', NULL, NULL, NULL),
(173, 'Mercado de trabalho atual saturado', NULL, NULL, NULL),
(174, 'Trabalho na área da minha segunda formação', NULL, NULL, NULL),
(175, 'Falta de oportunidade', NULL, NULL, NULL),
(176, 'Não preciso/ Não quero', NULL, NULL, NULL),
(177, 'Me dedico aos estudos', NULL, NULL, NULL),
(178, 'Aeroespacial e defesa', NULL, NULL, NULL),
(179, 'Automobilísticas', NULL, NULL, NULL),
(180, 'Fundos de aposentadoria e de pensão', NULL, NULL, NULL),
(181, 'Indústria farmacêutica', NULL, NULL, NULL),
(182, 'Maquinas e equipamentos', NULL, NULL, NULL),
(183, 'Organização sem fins lucrativos', NULL, NULL, NULL),
(184, 'Serviços', NULL, NULL, NULL),
(185, 'Setor público', NULL, NULL, NULL),
(186, 'Tecnologia da informação', NULL, NULL, NULL),
(187, 'Menos de 10', NULL, NULL, NULL),
(188, 'Entre 10 e 20', NULL, NULL, NULL),
(189, 'Entre 10 e 30', NULL, NULL, NULL),
(190, 'Entre 21 e 35', NULL, NULL, NULL),
(191, 'Entre 31 e 50', NULL, NULL, NULL),
(192, 'Entre 36 e 50', NULL, NULL, NULL),
(193, 'Entre 51 e 100', NULL, NULL, NULL),
(194, 'Mais de 100', NULL, NULL, NULL),
(195, 'Usa efetivamente', NULL, NULL, NULL),
(196, 'Usa indiretamente e é indispensável', NULL, NULL, NULL),
(197, 'Usa indiretamente e é dispensável', NULL, NULL, NULL),
(198, 'Nunca usei', NULL, NULL, NULL),
(199, 'Não fiz a disciplina', NULL, NULL, NULL),
(200, 'Não se aplica', NULL, NULL, NULL),
(201, 'Menos de 2 horas', NULL, NULL, NULL),
(202, '2 a 4 horas', NULL, NULL, NULL),
(203, '4 a 6 horas', NULL, NULL, NULL),
(204, '5 a 7 horas', NULL, NULL, NULL),
(205, '6 a 8 horas', NULL, NULL, NULL),
(206, '8 a 10 horas', NULL, NULL, NULL),
(207, 'Mais de 10 horas', NULL, NULL, NULL),
(208, 'Péssima', NULL, NULL, NULL),
(209, 'Ruim', NULL, NULL, NULL),
(210, 'Regular', NULL, NULL, NULL),
(211, 'Bom', NULL, NULL, NULL),
(212, 'Ótimo', NULL, NULL, NULL),
(213, 'Um pouco', NULL, NULL, NULL),
(214, 'Muito', NULL, NULL, NULL),
(215, 'Péssimo', NULL, NULL, NULL),
(216, 'Muito importante', NULL, NULL, NULL),
(217, 'Importante', NULL, NULL, NULL),
(218, 'Pouco importante', NULL, NULL, NULL),
(219, 'Sem importância', NULL, NULL, NULL),
(220, 'Sim. Em uma revista', NULL, NULL, NULL),
(221, 'Sim. Em um congresso', NULL, NULL, NULL),
(222, 'Sim. Em uma revista e em um congresso', NULL, NULL, NULL),
(223, 'Artigo', NULL, NULL, NULL),
(224, 'Monografia', NULL, NULL, NULL),
(225, 'Sim. Como diretor', NULL, NULL, NULL),
(226, 'Sim. Como gerente', NULL, NULL, NULL),
(227, 'Sim. Efetivo', NULL, NULL, NULL),
(228, 'Sim. Em outro cargo', NULL, NULL, NULL),
(229, 'Sim. Em mais de uma função', NULL, NULL, NULL),
(230, 'Sim. Na comissão coordenadora do curso', NULL, NULL, NULL),
(231, 'Sim. No DCE', NULL, NULL, NULL),
(232, 'Sim. Em ambas as entidade', NULL, NULL, NULL),
(233, 'Sim. Em outra entidade', NULL, NULL, NULL),
(234, 'Sim. Com bolsa', NULL, NULL, NULL),
(235, 'Sim. Sem bolsa', NULL, NULL, NULL),
(236, 'Sim. De uma matéria específica do curso', NULL, NULL, NULL),
(237, 'Sim. De uma matéria de outro curso', NULL, NULL, NULL),
(238, 'Sim. De ambos', NULL, NULL, NULL),
(239, 'Sim. Com e sem bolsa', NULL, NULL, NULL),
(240, 'Sim. No Brasil', NULL, NULL, NULL),
(241, 'Sim. No exterior', NULL, NULL, NULL);