use scadae;

INSERT INTO `subpergunta` (`id_subpergunta`, `subpergunta`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Inglês', NULL, NULL, NULL),
(2, 'Espanhol', NULL, NULL, NULL),
(3, 'Italiano', NULL, NULL, NULL),
(4, 'Francês', NULL, NULL, NULL),
(5, 'Apresentação em público', NULL, NULL, NULL),
(6, 'Falta de cursos relacionados a área', NULL, NULL, NULL),
(7, 'Fluência em línguas estrangeiras', NULL, NULL, NULL),
(8, 'Motivação da equipe', NULL, NULL, NULL),
(9, 'Outras', NULL, NULL, NULL),
(10, 'Instituição de ensino', NULL, NULL, NULL),
(11, 'Trabalho em equipe', NULL, NULL, NULL),
(12, 'Experiência no mercado', NULL, NULL, NULL),
(13, 'Fluência em línguas', NULL, NULL, NULL),
(14, 'Disponibilidade para hora extra', NULL, NULL, NULL),
(15, 'Mestrado/Doutorado/Especialização', NULL, NULL, NULL),
(16, 'Adaptação às mudanças', NULL, NULL, NULL),
(17, 'Aprendizado de novas técnicas', NULL, NULL, NULL),
(18, 'Aptidão empreendedora', NULL, NULL, NULL),
(19, 'Capacidade analítica', NULL, NULL, NULL),
(20, 'Criatividade', NULL, NULL, NULL),
(21, 'Eficiência na produção', NULL, NULL, NULL),
(22, 'Liderança', NULL, NULL, NULL),
(23, 'Visão ampla de organização', NULL, NULL, NULL),
(24, 'Visão de novas tendências', NULL, NULL, NULL),
(25, 'Algoritmo e estrutura de dados', NULL, NULL, NULL),
(26, 'Análise e projeto de sistemas', NULL, NULL, NULL),
(27, 'Arquitetura de software', NULL, NULL, NULL),
(28, 'Banco de dados', NULL, NULL, NULL),
(29, 'Cálculo diferencial e integral', NULL, NULL, NULL),
(30, 'Compiladores', NULL, NULL, NULL),
(31, 'Computador e sociedade', NULL, NULL, NULL),
(32, 'Contabilidade', NULL, NULL, NULL),
(33, 'Economia', NULL, NULL, NULL),
(34, 'Empreendedorismo e inovação', NULL, NULL, NULL),
(35, 'Engenharia de software', NULL, NULL, NULL),
(36, 'Estrutura da informação na web', NULL, NULL, NULL),
(37, 'Física', NULL, NULL, NULL),
(38, 'Fundamentos da administração', NULL, NULL, NULL),
(39, 'Fundamentos da teoria da computação', NULL, NULL, NULL),
(40, 'Geometria analítica e álgebra linear', NULL, NULL, NULL),
(41, 'Gestão ambiental', NULL, NULL, NULL),
(42, 'Gestão da diversidade nas organizações', NULL, NULL, NULL),
(43, 'Gestão da informação', NULL, NULL, NULL),
(44, 'Gestão de projetos', NULL, NULL, NULL),
(45, 'Iniciação à estatística', NULL, NULL, NULL),
(46, 'Informática básica', NULL, NULL, NULL),
(47, 'Inglês técnico', NULL, NULL, NULL),
(48, 'Introdução à ciência dos dados', NULL, NULL, NULL),
(49, 'Introdução à programação', NULL, NULL, NULL),
(50, 'Introdução aos sistemas lógicos e digitais', NULL, NULL, NULL),
(51, 'Legislação para informática', NULL, NULL, NULL),
(52, 'Lógica de programação', NULL, NULL, NULL),
(53, 'Libras', NULL, NULL, NULL),
(54, 'Linguagens de programação', NULL, NULL, NULL),
(55, 'Manutenção de computadores', NULL, NULL, NULL),
(56, 'Matematica discreta', NULL, NULL, NULL),
(57, 'Matematica financeira', NULL, NULL, NULL),
(58, 'Meta-heuristica', NULL, NULL, NULL),
(59, 'O ser e as organizações', NULL, NULL, NULL),
(60, 'Organização de computadores', NULL, NULL, NULL),
(61, 'Organização de computadores e sistemas operacionais', NULL, NULL, NULL),
(62, 'Pesquisa operacional', NULL, NULL, NULL),
(63, 'Português instrumental', NULL, NULL, NULL),
(64, 'Processamento digital de imagens', NULL, NULL, NULL),
(65, 'Programação', NULL, NULL, NULL),
(66, 'Programação orientada a objetos', NULL, NULL, NULL),
(67, 'Programação web', NULL, NULL, NULL),
(68, 'Projeto', NULL, NULL, NULL),
(69, 'Projeto de sistemas para web', NULL, NULL, NULL),
(70, 'Projeto de software orientado a dados', NULL, NULL, NULL),
(71, 'Projeto e análise de algoritmos', NULL, NULL, NULL),
(72, 'Redação teórica', NULL, NULL, NULL),
(73, 'Redes de computadores', NULL, NULL, NULL),
(74, 'Sistemas distribuidos e paralelos', NULL, NULL, NULL),
(75, 'Sistemas embarcados', NULL, NULL, NULL),
(76, 'Sistemas operacionais', NULL, NULL, NULL),
(77, 'Teoria e modelo de grafos', NULL, NULL, NULL),
(78, 'Teoria geral da administração', NULL, NULL, NULL),
(79, 'Tópicos especiais III', NULL, NULL, NULL),
(80, 'Tópicos especiais IV', NULL, NULL, NULL),
(82, 'Tópicos especiais em informática', NULL, NULL, NULL),
(83, '.Net', NULL, NULL, NULL),
(84, 'ASP', NULL, NULL, NULL),
(85, 'Assembly', NULL, NULL, NULL),
(86, 'C', NULL, NULL, NULL),
(87, 'C++', NULL, NULL, NULL),
(88, 'C#', NULL, NULL, NULL),
(89, 'Cobol', NULL, NULL, NULL),
(90, 'Delphi', NULL, NULL, NULL),
(91, 'Go', NULL, NULL, NULL),
(92, 'Java', NULL, NULL, NULL),
(93, 'JavaScript', NULL, NULL, NULL),
(94, 'Kotlin', NULL, NULL, NULL),
(95, 'ML', NULL, NULL, NULL),
(96, 'Objective-C', NULL, NULL, NULL),
(97, 'Pascal', NULL, NULL, NULL),
(98, 'PHP', NULL, NULL, NULL),
(99, 'Python', NULL, NULL, NULL),
(100, 'R', NULL, NULL, NULL),
(101, 'Ruby', NULL, NULL, NULL),
(102, 'TypeScript', NULL, NULL, NULL),
(103, 'Visual Basic', NULL, NULL, NULL),
(104, 'Verilog', NULL, NULL, NULL),
(105, 'Db2', NULL, NULL, NULL),
(106, 'Cache', NULL, NULL, NULL),
(107, 'Microsoft Acces', NULL, NULL, NULL),
(108, 'Microsoft Sql Server', NULL, NULL, NULL),
(109, 'MongoDB', NULL, NULL, NULL),
(110, 'Mysql', NULL, NULL, NULL),
(111, 'Oracle', NULL, NULL, NULL),
(112, 'Paradx', NULL, NULL, NULL),
(113, 'PostgreSQL', NULL, NULL, NULL),
(114, 'Teradata', NULL, NULL, NULL),
(115, 'Outros', NULL, NULL, NULL),
(116, 'Linux', NULL, NULL, NULL),
(117, 'MacOS', NULL, NULL, NULL),
(118, 'Netware', NULL, NULL, NULL),
(119, 'Windows', NULL, NULL, NULL),
(120, 'Atletismo', NULL, NULL, NULL),
(121, 'Basquete', NULL, NULL, NULL),
(122, 'Futebol', NULL, NULL, NULL),
(123, 'Musculação', NULL, NULL, NULL),
(124, 'Vôlei', NULL, NULL, NULL),
(125, 'Curso fácil de entrar', NULL, NULL, NULL),
(126, 'Curso fácil de fazer', NULL, NULL, NULL),
(127, 'Interesse na área', NULL, NULL, NULL),
(128, 'Mercado de trabalho', NULL, NULL, NULL),
(129, 'Custo de vida', NULL, NULL, NULL),
(130, 'Infraestrutura', NULL, NULL, NULL),
(131, 'Localidade', NULL, NULL, NULL),
(132, 'Menor nota para entrar', NULL, NULL, NULL),
(133, 'Possibilidade de bolsa', NULL, NULL, NULL),
(134, 'Aulas', NULL, NULL, NULL),
(135, 'Biblioteca', NULL, NULL, NULL),
(136, 'Laboratórios', NULL, NULL, NULL),
(137, 'Salas de aula', NULL, NULL, NULL),
(138, 'Outras dependências', NULL, NULL, NULL),
(139, 'Graduação', NULL, NULL, NULL),
(140, 'Falta de outra opção', NULL, NULL, NULL);