<?php
    include '../acessobancotec.php';
    include 'vTecnico.php';

    $teste_tecnologiatec = "SELECT * 
                            FROM resposta
	                        WHERE CPF = '$cpf' AND id_perguntas = (SELECT id_perguntas 
                                                                   FROM pergunta 
                                                                   WHERE numeracao = 41)";
	          
    $verifica_tecnologiatec = mysqli_query($conn, $teste_tecnologiatec);

    if (mysqli_num_rows($verifica_tecnologiatec) >= 1){
        $delete41 = "DELETE FROM resposta WHERE cpf = '$cpf' AND id_perguntas = (SELECT id_perguntas FROM pergunta WHERE numeracao = 41);";
        $delete42 = "DELETE FROM resposta WHERE cpf = '$cpf' AND id_perguntas = (SELECT id_perguntas FROM pergunta WHERE numeracao = 42);";
        $delete43 = "DELETE FROM resposta WHERE cpf = '$cpf' AND id_perguntas = (SELECT id_perguntas FROM pergunta WHERE numeracao = 43);"; 
        
        $d41 = mysqli_query($conn, $delete41);
        $d42 = mysqli_query($conn, $delete42);
        $d43 = mysqli_query($conn, $delete43);
    }
                
    $opt41A = filter_input (INPUT_POST, '41A', FILTER_SANITIZE_STRING);
    $opt41B = filter_input (INPUT_POST, '41B', FILTER_SANITIZE_STRING);
    $opt41C = filter_input (INPUT_POST, '41C', FILTER_SANITIZE_STRING);
    $opt41D = filter_input (INPUT_POST, '41D', FILTER_SANITIZE_STRING);
    $opt41E = filter_input (INPUT_POST, '41E', FILTER_SANITIZE_STRING);
    $opt41F = filter_input (INPUT_POST, '41F', FILTER_SANITIZE_STRING);
    $opt41G = filter_input (INPUT_POST, '41G', FILTER_SANITIZE_STRING);
    $opt41H = filter_input (INPUT_POST, '41H', FILTER_SANITIZE_STRING);
    $opt41I = filter_input (INPUT_POST, '41I', FILTER_SANITIZE_STRING);
    $opt41J = filter_input (INPUT_POST, '41J', FILTER_SANITIZE_STRING);
    $opt41K = filter_input (INPUT_POST, '41K', FILTER_SANITIZE_STRING);
    $opt41L = filter_input (INPUT_POST, '41L', FILTER_SANITIZE_STRING);
    $opt41M = filter_input (INPUT_POST, '41M', FILTER_SANITIZE_STRING);
    $opt41N = filter_input (INPUT_POST, '41N', FILTER_SANITIZE_STRING);
    $opt41O = filter_input (INPUT_POST, '41O', FILTER_SANITIZE_STRING);
    $opt41P = filter_input (INPUT_POST, '41P', FILTER_SANITIZE_STRING);
    $opt41Q = filter_input (INPUT_POST, '41Q', FILTER_SANITIZE_STRING);
    $opt41R = filter_input (INPUT_POST, '41R', FILTER_SANITIZE_STRING);
    $opt41S = filter_input (INPUT_POST, '41S', FILTER_SANITIZE_STRING);
    $opt41T = filter_input (INPUT_POST, '41T', FILTER_SANITIZE_STRING);
    $opt41U = filter_input (INPUT_POST, '41U', FILTER_SANITIZE_STRING);
    $opt41V = filter_input (INPUT_POST, '41V', FILTER_SANITIZE_STRING);
    $opt41W = filter_input (INPUT_POST, '41W', FILTER_SANITIZE_STRING);
    $opt42A = filter_input (INPUT_POST, '42A', FILTER_SANITIZE_STRING);
    $opt42B = filter_input (INPUT_POST, '42B', FILTER_SANITIZE_STRING);
    $opt42C = filter_input (INPUT_POST, '42C', FILTER_SANITIZE_STRING);
    $opt42D = filter_input (INPUT_POST, '42D', FILTER_SANITIZE_STRING);
    $opt42E = filter_input (INPUT_POST, '42E', FILTER_SANITIZE_STRING);
    $opt42F = filter_input (INPUT_POST, '42F', FILTER_SANITIZE_STRING);
    $opt42G = filter_input (INPUT_POST, '42G', FILTER_SANITIZE_STRING);
    $opt42H = filter_input (INPUT_POST, '42H', FILTER_SANITIZE_STRING);
    $opt42I = filter_input (INPUT_POST, '42I', FILTER_SANITIZE_STRING);
    $opt42J = filter_input (INPUT_POST, '42J', FILTER_SANITIZE_STRING);
    $opt42K = filter_input (INPUT_POST, '42K', FILTER_SANITIZE_STRING);
    $opt43A = filter_input (INPUT_POST, '43A', FILTER_SANITIZE_STRING);
    $opt43B = filter_input (INPUT_POST, '43B', FILTER_SANITIZE_STRING);
    $opt43C = filter_input (INPUT_POST, '43C', FILTER_SANITIZE_STRING);
    $opt43D = filter_input (INPUT_POST, '43D', FILTER_SANITIZE_STRING);
    $opt43E = filter_input (INPUT_POST, '43E', FILTER_SANITIZE_STRING);
    $opt43F = filter_input (INPUT_POST, '43F', FILTER_SANITIZE_STRING);
                
    $insert41A = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41A' AND numeracao = 41 AND numero = 'A'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'A' AND alternativa = '$opt41A'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'A' AND numeracao = 41));";
    $insert41B = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41B' AND numeracao = 41 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'B' AND alternativa = '$opt41B'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'B' AND numeracao = 41));";
    $insert41C = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41C' AND numeracao = 41 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'C' AND alternativa = '$opt41C'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'C' AND numeracao = 41));";
    $insert41D = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41D' AND numeracao = 41 AND numero = 'D'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'D' AND alternativa = '$opt41D'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'D' AND numeracao = 41));";
    $insert41E = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41E' AND numeracao = 41 AND numero = 'E'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'E' AND alternativa = '$opt41E'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'E' AND numeracao = 41));";
    $insert41F = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41F' AND numeracao = 41 AND numero = 'F'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'F' AND alternativa = '$opt41F'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'F' AND numeracao = 41));";
    $insert41G = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41G' AND numeracao = 41 AND numero = 'G'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'G' AND alternativa = '$opt41G'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'G' AND numeracao = 41));";
    $insert41H = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41H' AND numeracao = 41 AND numero = 'H'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'H' AND alternativa = '$opt41H'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'H' AND numeracao = 41));";
    $insert41I = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41I' AND numeracao = 41 AND numero = 'I'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'I' AND alternativa = '$opt41I'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'I' AND numeracao = 41));";
    $insert41J = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41J' AND numeracao = 41 AND numero = 'J'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'J' AND alternativa = '$opt41J'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'J' AND numeracao = 41));";
    $insert41K = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41K' AND numeracao = 41 AND numero = 'K'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'K' AND alternativa = '$opt41K'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'K' AND numeracao = 41));";
    $insert41L = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41L' AND numeracao = 41 AND numero = 'L'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'L' AND alternativa = '$opt41L'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'L' AND numeracao = 41));";
    $insert41M = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41M' AND numeracao = 41 AND numero = 'M'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'M' AND alternativa = '$opt41M'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'M' AND numeracao = 41));";
    $insert41N = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41N' AND numeracao = 41 AND numero = 'N'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'N' AND alternativa = '$opt41N'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'N' AND numeracao = 41));";
    $insert41O = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41O' AND numeracao = 41 AND numero = 'O'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'O' AND alternativa = '$opt41O'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'O' AND numeracao = 41));";
    $insert41P = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41P' AND numeracao = 41 AND numero = 'P'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'P' AND alternativa = '$opt41P'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'P' AND numeracao = 41));";
    $insert41Q = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41Q' AND numeracao = 41 AND numero = 'Q'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'Q' AND alternativa = '$opt41Q'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'Q' AND numeracao = 41));";
    $insert41R = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41R' AND numeracao = 41 AND numero = 'R'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'R' AND alternativa = '$opt41R'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'R' AND numeracao = 41));";
    $insert41S = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41S' AND numeracao = 41 AND numero = 'S'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'S' AND alternativa = '$opt41S'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'S' AND numeracao = 41));";
    $insert41T = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41T' AND numeracao = 41 AND numero = 'T'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'T' AND alternativa = '$opt41T'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'T' AND numeracao = 41));";
    $insert41U = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41U' AND numeracao = 41 AND numero = 'U'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'U' AND alternativa = '$opt41U'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'U' AND numeracao = 41));";
    $insert41V = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41V' AND numeracao = 41 AND numero = 'V'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'V' AND alternativa = '$opt41V'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'V' AND numeracao = 41));";
    $insert41W = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt41W' AND numeracao = 41 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 41), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 41 AND numero = 'W' AND alternativa = '$opt41W'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'W' AND numeracao = 41));";
    $insert42A = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42A' AND numeracao = 42 AND numero = 'A'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'A' AND alternativa = '$opt42A'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'A' AND numeracao = 42));";
    $insert42B = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42B' AND numeracao = 42 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'B' AND alternativa = '$opt42B'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'B' AND numeracao = 42));";
    $insert42C = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42C' AND numeracao = 42 AND numero = 'C'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'C' AND alternativa = '$opt42C'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'C' AND numeracao = 42));";
    $insert42D = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42D' AND numeracao = 42 AND numero = 'D'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'D' AND alternativa = '$opt42D'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'D' AND numeracao = 42));";
    $insert42E = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42E' AND numeracao = 42 AND numero = 'E'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'E' AND alternativa = '$opt42E'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'E' AND numeracao = 42));";
    $insert42F = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42F' AND numeracao = 42 AND numero = 'F'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'F' AND alternativa = '$opt42F'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'F' AND numeracao = 42));";
    $insert42G = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42G' AND numeracao = 42 AND numero = 'G'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'G' AND alternativa = '$opt42G'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'G' AND numeracao = 42));";
    $insert42H = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42H' AND numeracao = 42 AND numero = 'H'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'H' AND alternativa = '$opt42H'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'H' AND numeracao = 42));";
    $insert42I = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42I' AND numeracao = 42 AND numero = 'I'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'I' AND alternativa = '$opt42I'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'I' AND numeracao = 42));";
    $insert42J = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42J' AND numeracao = 42 AND numero = 'J'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'J' AND alternativa = '$opt42J'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'J' AND numeracao = 42));";
    $insert42K = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt42K' AND numeracao = 42 AND numero = 'K'), (SELECT id_perguntas FROM pergunta where numeracao = 42), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 42 AND numero = 'K' AND alternativa = '$opt42K'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'K' AND numeracao = 42));";
    $insert43A = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt43A' AND numeracao = 43 AND numero = 'A'), (SELECT id_perguntas FROM pergunta where numeracao = 43), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 43 AND numero = 'A' AND alternativa = '$opt43A'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'A' AND numeracao = 43));";
    $insert43B = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt43B' AND numeracao = 43 AND numero = 'B'), (SELECT id_perguntas FROM pergunta where numeracao = 43), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 43 AND numero = 'B' AND alternativa = '$opt43B'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'B' AND numeracao = 43));";
    $insert43C = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt43C' AND numeracao = 43 AND numero = 'C'), (SELECT id_perguntas FROM pergunta where numeracao = 43), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 43 AND numero = 'C' AND alternativa = '$opt43C'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'C' AND numeracao = 43));";
    $insert43D = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt43D' AND numeracao = 43 AND numero = 'D'), (SELECT id_perguntas FROM pergunta where numeracao = 43), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 43 AND numero = 'D' AND alternativa = '$opt43D'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'D' AND numeracao = 43));";
    $insert43E = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt43E' AND numeracao = 43 AND numero = 'E'), (SELECT id_perguntas FROM pergunta where numeracao = 43), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 43 AND numero = 'E' AND alternativa = '$opt43E'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'E' AND numeracao = 43));";
    $insert43F = "INSERT INTO resposta(cpf, resposta, id_perguntas, id_alternativa, id_subpergunta) VALUES ('$cpf', (SELECT opcao FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa where alternativa = '$opt43F' AND numeracao = 43 AND numero = 'F'), (SELECT id_perguntas FROM pergunta where numeracao = 43), (SELECT id_alternativa FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta NATURAL JOIN subpergunta_has_alternativa NATURAL JOIN alternativa WHERE numeracao = 43 AND numero = 'F' AND alternativa = '$opt43F'), (SELECT id_subpergunta FROM pergunta NATURAL JOIN subpergunta_has_pergunta NATURAL JOIN subpergunta WHERE numero = 'F' AND numeracao = 43));";
                
    $resultado41A = mysqli_query($conn, $insert41A);
    $resultado41B = mysqli_query($conn, $insert41B);
    $resultado41C = mysqli_query($conn, $insert41C);
    $resultado41D = mysqli_query($conn, $insert41D);
    $resultado41E = mysqli_query($conn, $insert41E);
    $resultado41F = mysqli_query($conn, $insert41F);
    $resultado41G = mysqli_query($conn, $insert41G);
    $resultado41H = mysqli_query($conn, $insert41H);
    $resultado41I = mysqli_query($conn, $insert41I);
    $resultado41J = mysqli_query($conn, $insert41J);
    $resultado41K = mysqli_query($conn, $insert41K);
    $resultado41L = mysqli_query($conn, $insert41L);
    $resultado41M = mysqli_query($conn, $insert41M);
    $resultado41N = mysqli_query($conn, $insert41N);
    $resultado41O = mysqli_query($conn, $insert41O);
    $resultado41P = mysqli_query($conn, $insert41P);
    $resultado41Q = mysqli_query($conn, $insert41Q);
    $resultado41R = mysqli_query($conn, $insert41R);
    $resultado41S = mysqli_query($conn, $insert41S);
    $resultado41T = mysqli_query($conn, $insert41T);
    $resultado41U = mysqli_query($conn, $insert41U);
    $resultado41V = mysqli_query($conn, $insert41V);
    $resultado41W = mysqli_query($conn, $insert41W);
    $resultado42A = mysqli_query($conn, $insert42A);
    $resultado42B = mysqli_query($conn, $insert42B);
    $resultado42C = mysqli_query($conn, $insert42C);
    $resultado42D = mysqli_query($conn, $insert42D);
    $resultado42E = mysqli_query($conn, $insert42E);
    $resultado42F = mysqli_query($conn, $insert42F);
    $resultado42G = mysqli_query($conn, $insert42G);
    $resultado42H = mysqli_query($conn, $insert42H);
    $resultado42I = mysqli_query($conn, $insert42I);
    $resultado42J = mysqli_query($conn, $insert42J);
    $resultado42K = mysqli_query($conn, $insert42K);
    $resultado43A = mysqli_query($conn, $insert43A);
    $resultado43B = mysqli_query($conn, $insert43B);
    $resultado43C = mysqli_query($conn, $insert43C);
    $resultado43D = mysqli_query($conn, $insert43D);
    $resultado43E = mysqli_query($conn, $insert43E);
    $resultado43F = mysqli_query($conn, $insert43F);

    mysqli_close($conn);

    
    header ("Location: lazertec.php");
?>